apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psap-control-center-data
  labels:
    app: psap-control-center
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psap-control-center-kubeconfigs
  labels:
    app: psap-control-center
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
